DROP TABLE IF EXISTS `announcement`;
DROP TABLE IF EXISTS `course`;
DROP TABLE IF EXISTS `group`;
DROP TABLE IF EXISTS `group_member`;
DROP TABLE IF EXISTS `homework`;
DROP TABLE IF EXISTS `resource`;
DROP TABLE IF EXISTS `student`;
DROP TABLE IF EXISTS `teacher`;