-- 清表
TRUNCATE TABLE `announcement`;
TRUNCATE TABLE `course`;
TRUNCATE TABLE `group`;
TRUNCATE TABLE `group_member`;
TRUNCATE TABLE `homework`;
TRUNCATE TABLE `homework_upload`;
TRUNCATE TABLE `resource`;
TRUNCATE TABLE `score`;
TRUNCATE TABLE `student`;
TRUNCATE TABLE `teacher`;
-- 插入数据
INSERT INTO STUDENT (GMT_CREATE, GMT_MODIFIED, STUDENT_ID, PASSWORD, NAME, GENDER, CLASS)
VALUES (NOW(), NOW(), 14212333, '123456', '测试用户', 1, 14215);
INSERT INTO STUDENT (GMT_CREATE, GMT_MODIFIED, STUDENT_ID, PASSWORD, NAME, GENDER, CLASS)
VALUES (NOW(), NOW(), 14211133, '123456', 'TONY', 1, 14215);
INSERT INTO TEACHER (GMT_CREATE, GMT_MODIFIED, TEACHER_ID, PASSWORD, NAME, EMAIL)
VALUES (NOW(), NOW(), 'T001', 'T001', '林广艳', 'lingy@buaa.edu.cn');
INSERT INTO ANNOUNCEMENT (GMT_CREATE, GMT_MODIFIED, ANNOUNCEMENT_ID, COURSE_ID, TEACHER_ID, TITLE, MESSAGE, START_TIME, END_TIME)
VALUES (NOW(), NOW(), '1', '1', 'T001', '准时上课', '请大家于9：00准时到达工训317', '2017-07-27 09:00:00', '2017-07-27 10:00:00');
INSERT INTO ANNOUNCEMENT (GMT_CREATE, GMT_MODIFIED, ANNOUNCEMENT_ID, COURSE_ID, TEACHER_ID, TITLE, MESSAGE, START_TIME, END_TIME)
VALUES (NOW(), NOW(), '2', '1', 'T001', '准时提交作业', '请大家于9：00准时提交作业', '2017-07-27 09:00:00', '2017-07-27 10:00:00');
INSERT INTO COURSE (GMT_CREATE, GMT_MODIFIED, COURSE_ID, COURSE_START_TIME, COURSE_END_TIME, COURSE_NAME, COURSE_HOURS, CREDIT, COURSE_LOCATION, TEAM_LIMIT_INFORMATION, TEACHER_INFORMATION, COURSE_INFORMATION)
VALUES (NOW(), NOW(), '1', '2017-06-25', '2017-07-05', '春季软件开发实践', '120', '2', '工训317', '6-8人', '林广艳', '签到很严格');
INSERT INTO `GROUP` (GMT_CREATE, GMT_MODIFIED, COURSE_ID, GROUP_ID, GROUP_NAME, GROUP_OWNER_ID, GROUP_SCORE, GROUP_STATUS)
VALUES (NOW(), NOW(), '1', '1', 'other', '14212333', 90, '0');
INSERT INTO `GROUP` (GMT_CREATE, GMT_MODIFIED, COURSE_ID, GROUP_ID, GROUP_NAME, GROUP_OWNER_ID, GROUP_SCORE, GROUP_STATUS)
VALUES (NOW(), NOW(), '1', '2', 'other2', '14211083', 90, '0');
INSERT INTO GROUP_MEMBER (GMT_CREATE, GMT_MODIFIED, COURSE_ID, GROUP_ID, STUDENT_ID, GROUP_ROLE)
VALUES (NOW(), NOW(), '1', '1', '14211088', '0');
INSERT INTO GROUP_MEMBER (GMT_CREATE, GMT_MODIFIED, COURSE_ID, GROUP_ID, STUDENT_ID, GROUP_ROLE)
VALUES (NOW(), NOW(), '1', '1', '14212333', '1');
INSERT INTO HOMEWORK (GMT_CREATE, GMT_MODIFIED, COURSE_ID, HOMEWORK_ID, TEACHER_ID, STATUS, TITLE, MESSAGE, START_TIME, END_TIME, RESUBMIT_LIMIT, RESUBMIT_LIMIT_TIME)
VALUES (NOW(), NOW(), '1', '1', 'T001', '0', '作业1', '提交用户故事', '2017-06-25 09:00:00', '2017-06-25 17:00:00', 3,
        '2017-06-25,14:00:00');
INSERT INTO HOMEWORK (GMT_CREATE, GMT_MODIFIED, COURSE_ID, HOMEWORK_ID, TEACHER_ID, STATUS, TITLE, MESSAGE, START_TIME, END_TIME, RESUBMIT_LIMIT, RESUBMIT_LIMIT_TIME)
VALUES (NOW(), NOW(), '1', '2', 'T001', '0', '作业2', '提交迭代计划', '2017-06-25 09:00:00', '2017-06-25 17:00:00', 3,
        '2017-06-25,14:00:00');
INSERT INTO HOMEWORK_UPLOAD (GMT_CREATE, GMT_MODIFIED, COURSE_ID, HOMEWORK_ID, HOMEWORK_UPLOAD_ID, GROUP_ID, HOMEWORK_URL, MESSAGE, HOMEWORK_UPLOAD_TIME)
VALUES (NOW(), NOW(), '1', '1', '1', '1', 'URL', '用户故事', NOW());
INSERT INTO HOMEWORK_UPLOAD (GMT_CREATE, GMT_MODIFIED, COURSE_ID, HOMEWORK_ID, HOMEWORK_UPLOAD_ID, GROUP_ID, HOMEWORK_URL, MESSAGE, HOMEWORK_UPLOAD_TIME)
VALUES (NOW(), NOW(), '1', '1', '2', '2', 'URL', '迭代计划', NOW());
INSERT INTO RESOURCE (GMT_CREATE, GMT_MODIFIED, RESOURCE_ID, COURSE_ID, TEACHER_ID, RESOURCE_TYPE, TITLE, RESOURCE_URL, RESOURCE_SIZE, LAST_UPDATE_TIME)
VALUES (NOW(), NOW(), '1', '1', 'T001', '0', '资源1', 'URL', 20, NOW());
INSERT INTO RESOURCE (GMT_CREATE, GMT_MODIFIED, RESOURCE_ID, COURSE_ID, TEACHER_ID, RESOURCE_TYPE, TITLE, RESOURCE_URL, RESOURCE_SIZE, LAST_UPDATE_TIME)
VALUES (NOW(), NOW(), '2', '1', 'T001', '0', '资源2', 'URL', 30, NOW());
INSERT INTO SCORE (GMT_CREATE, GMT_MODIFIED, SCORE_ID, COURSE_ID, GRADER_ID, GROUP_ID, HOMEWORK_ID, SCORE, MESSAGE, SCORE_TIME)
VALUES (NOW(), NOW(), '1', '1', 'T001', '1', '1', 30, '完成的不错', NOW());
INSERT INTO SCORE (GMT_CREATE, GMT_MODIFIED, SCORE_ID, COURSE_ID, GRADER_ID, GROUP_ID, HOMEWORK_ID, SCORE, MESSAGE, SCORE_TIME)
VALUES (NOW(), NOW(), '1', '1', '14212333', '1', '1', 90, '完成的不错', NOW());