INSERT INTO STUDENT (GMT_CREATE, GMT_MODIFIED, STUDENT_ID, PASSWORD, NAME, GENDER, CLASS)
VALUES (NOW(), NOW(), 14212333, 1234, '测试用户', 1, 14215);
INSERT INTO STUDENT (GMT_CREATE, GMT_MODIFIED, STUDENT_ID, PASSWORD, NAME, GENDER, CLASS)
VALUES (NOW(), NOW(), 14211133, '1234qwer', 'TONY', 1, 14215);
INSERT INTO TEACHER (GMT_CREATE, GMT_MODIFIED, TEACHER_ID, PASSWORD, NAME, email)
VALUES (NOW(), NOW(), 'T001', 'T001', '林广艳', 'lingy@buaa.edu.cn');
